title: Tu Ba Khuym
email: hoang@kieng.io.vn
description: A place where I share my documents and knowledge
author: Tu Ba Khuym
baseurl: ""
url: "https://tubakhuym.kieng.io.vn"

# Social Profiles
twitter_username: 
github_username: hoangnb24
facebook_username: 
instagram_username:
linkedin_username:

# Build settings
markdown: kramdown
remote_theme: StartBootstrap/startbootstrap-clean-blog-jekyll
paginate: 5
paginate_path: "/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
